export const brand = {
  name: "StickerFizz BD",
  displayName: "StickerFizz BD",
  logo: "/stickerfizzbd-logo.png",
  followers: "6.2K followers",
  tagline: "We turn ideas into reality",
  sparkleTagline: "We turn ideas into reality",
  description: "Premium custom stickers & phone cases",
  quality: "Waterproof print quality",
  orderPrompt: "COD available across Bangladesh",
  service: "Printing service",
  priceSignal: "Sticker price: Tk 13/sq inch",
  email: "stickerfizzbd@gmail.com",
  phone: "+880 1307-910224",
  instagram: "stickerfizzbd",
  facebook: "Stickerfizzbd",
  instagramUrl: "https://instagram.com/stickerfizzbd",
  facebookUrl: "https://facebook.com/profile.php?id=61584629323897",
  siteUrl: "https://stickerfizzbd.com",
};
